### ISSUE TITLE
"Error In Your Request The e-mail address you have provided already exists in the mailing list(s) you have selected to subscribe to." 

### ISSUE THREAD

**Issue by life777eternal** [ListMessenger/listmessenger-pro#4]
> The [e-mail address](https://ccc-contact-finder.toallchurches.net) you have provided already exists in the mailing list(s) you have selected to subscribe to.

Greetings, I just upgraded from 2.2.1 to 2.2.3, and the subscribe form page is still forwarding to this message.

![email exists-Error In Your Request - Brave](https://github.com/ListMessenger/listmessenger-pro/assets/25623649/25af389b-0bb8-47b5-a133-ccdf0c02fe44)

The same thing is happening with my proton email address too.

Had this issue before I upgraded, and it's still present, so would it really be a problem just on my website domain? 

I thought it might have been because an email was not showing up in the list yet, because it wasn't confirmed, though I removed an email address of my own from the list and when I tried to use the form to subscribe, it showed the same thing. Why isn't there any list of emails that are not yet confirmed? 

Thank you, Shalom.

**Comment by mattsimpson** [comment]
Hello. For support requests, please connect on Discord.

**Comment by life777eternal** [comment]
Ok, alright then, thanks @mattsimpson  … Also why is there only one text channel in the Discord group? There should be a separate text channel for support requests.  Also I don't know why you can't help me here, are you sure this is not a bug?
